### ISSUE TITLE
Link files together as modules

### ISSUE THREAD

**Issue by kgudel** [cfpb/zip-backfill#5]
This would allow one to run the tests with a single command instead of running several command line scripts one by one.

**Comment by kgudel** [comment]
I can use .py files as modules and import them as I would any other module. I have refactored all of my files so that they should be able to successfully work as both (I have put all of the code in each file into functions except for a 'if **name** == **main**' statement to run a command line parser and the functions).

However, attempting to run the function pick_rows from the file pick_rand.py fails. This function calls the function choose_rows which creates a list of rows to pick from the input file, it takes the number of rows and the number of rows to pick, and uses random.sample(number of rows, number to pick). When running a file with many millions of rows and attempting to pick 10:

``` shell
~/zip_backfill kgudel* 👾  python test.py /users/gudelk/documents/openaddr-collected-us_all/zips.csv /users/gudelk/documents/backfill_test_self.csv /users/gudelk/downloads/tl_2015_us_zcta510/tl_2015_us_zcta510.shp 10 -o
```

it displays:

``` shell
picks rows
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    pick_rand.pick_rows(args.input, temp_rand, args.number)
  File "/Users/gudelk/zip_backfill/pick_rand.py", line 20, in pick_rows
    picks = deque(choose_rows(file_len(inputF), number))
  File "/Users/gudelk/zip_backfill/pick_rand.py", line 16, in choose_rows
    picks = random.sample(xrange(length), number)
  File "/Users/gudelk/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population
```

However, the code displays no errors picking 10 from the same file if running the pick_rand.py directly.

**Comment by awolfe76** [comment]
Like @kgudel I'm able to replicate the issue using

``` python
python test.py ~/Documents/test.csv ~/Documents/test-result.csv ~/Downloads/tl_2015_us_zcta510.zip 10 -o
```

and have it be successful directly using

```
python pick_rand.py ~/Documents/test.csv ~/Documents/test-rand.csv 10
```

---

Some tests I ran:
_Using `print len(range(length))` because that's how random.sample does it's check._

## 1

Adding

``` python
print len(range(length))
print number
picks = random.sample(range(length), number)
print sorted(picks)
```

to `pick_rand.py` shows that the arguments for `random.sample` are fine, 10718509 and 10, but random.sample still fails. Output:

``` shell
10718509
10
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    pick_rand.write_rows(args.input, temp_rand, args.number)
  File "/Users/wolfea/Documents/projects/zip-backfill/pick_rand.py", line 24, in write_rows
    picks = deque(choose_rows(file_len(inputF), number))
  File "/Users/wolfea/Documents/projects/zip-backfill/pick_rand.py", line 17, in choose_rows
    picks = random.sample(range(length), number)
  File "/Users/wolfea/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population
```

## 2

Calling

``` python
pick_rand.choose_rows(10718509, 10)
```

from `test.py` works fine. Example output:

```
10718509
10
[601868, 1666395, 1771443, 3103258, 3965187, 4504986, 6063613, 7278149, 8337408, 9683527]
```

## 3

Calling

``` python
choose_rows(10718509, 10)
```

from the `write_rows` function in `pick_rand.py` works fine as well. Example output:

```
10718509
10
[858471, 1162707, 1997237, 2042753, 5830800, 5898246, 7470345, 8790648, 9975243, 9998363]
```

_The `10718509` is the number of rows that happen to be in my `.csv` which you can see in the output from test 1._
